# Generated by Django 4.2.3 on 2023-08-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ER1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='first',
        ),
        migrations.DeleteModel(
            name='second',
        ),
    ]
